# Generated by Django 2.2.7 on 2019-11-28 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notation',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
