# Generated by Django 2.2.7 on 2019-11-28 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191128_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='notation',
            name='note',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
