# Generated by Django 2.2.7 on 2019-11-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_notation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='notation',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
